spring:
  jackson:
    date-format: yyyy-MM-dd
    serialization:
      write-dates-as-timestamps: false

jwt:
  secret: mySuperSecretKeyForJWTTokenGenerationThatIsAtLeast32BytesLong2024!
  expiration: 86400000 # 24 hours in milliseconds

server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always