spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/study_db}
    username: ${SPRING_DATASOURCE_USERNAME:study_user}
    password: ${SPRING_DATASOURCE_PASSWORD:study_password}
    driver-class-name: org.postgresql.Driver
  jackson:
    date-format: yyyy-MM-dd
    serialization:
      write-dates-as-timestamps: false
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    password: ${SPRING_REDIS_PASSWORD:redis_password}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: social-net-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 1  # Для одиночных - 1, для batch - 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "ru.otus.study.dto"
        spring.json.type.mapping: |
          postMessage:ru.otus.study.dto.PostMessage,
          feedUpdateTask:ru.otus.study.dto.FeedUpdateTask
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      retries: 3
      properties:
        spring.json.type.mapping: |
          postMessage:ru.otus.study.dto.PostMessage,
          feedUpdateTask:ru.otus.study.dto.FeedUpdateTask
    listener:
      ack-mode: manual
    admin:
      auto-create: true

app:
  celebrity:
    threshold: 10        # Количество постов
    window-minutes: 5    # За период (минут)
    batch-size: 100      # Размер батча для обновления
    materialize-delay: 1000  # Задержка перед материализацией (мс)
jwt:
  secret: ${JWT_SECRET:mySuperSecretKeyForJWTTokenGenerationThatIsAtLeast32BytesLong2024!}
  expiration: ${JWT_EXPIRATION:86400000}
server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always